---
resource_types:
  - name: workflow-events
    type: docker-image
    source:
      repository: openstax/workflow-event-resource

  - name: s3-dir
    type: docker-image
    source:
      repository: docker-registry:5000/s3-dir-resource
      tag: 0.1
      insecure_registries: ["docker-registry:5000"]

resources:
  - name: s3-job-dir
    type: s3-dir
    source:
      service:
        bucket: ((s3-bucket))
        region: ((s3-region))
        endpoint: ((s3-endpoint))
      credentials:
        access_key_id: ((s3-access-key-id))
        secret_access_key: ((s3-secret-access-key))
      filters:
        regexp: (\d+)
        version: latest

  - name: cnx-recipes
    type: git
    source:
      uri: https://github.com/openstax/cnx-recipes.git

  - name: pdf-spike
    type: git
    source:
      uri: https://github.com/openstax/pdf-spike.git
      branch: s3-resource-custom

  - name: workflow-events-queued
    type: workflow-events
    source:
      api_root: ((pdf-job-queue-url))
      status_id: 1
    check_every: 20s

  - name: event-update
    type: workflow-events
    source:
      api_root: ((pdf-job-queue-url))
      status_id: 0

jobs:
  - name: claim-work
    plan:
      - get: workflow-events-queued
        trigger: true
        version: every
      - put: event-update
        params:
          id: workflow-events-queued/id
          status_id: "2" #Assigned

    on_success:
      put: event-update
      params:
        id: workflow-events-queued/id
        status_id: "3" #Processing

  - name: fetch-book
    plan:
      - get: workflow-events-queued
        trigger: true
        passed: [claim-work]
      - get: pdf-spike
      - task: look-up-book
        file: pdf-spike/bakery/tasks/t-book-lookup.yml
      - task: fetch-book-via-neb
        file: pdf-spike/bakery/tasks/t-fetch-book.yml

    on_failure:
      put: event-update
      params:
        id: workflow-events-queued/id
        status_id: "4" #Failed
    on_success:
      put: s3-job
      params:
        dir: workflow-events-queued/id
        glob: book/**/*

  - name: assemble-book
    plan:
      - get: workflow-events-queued
        trigger: true
        passed: [fetch-book]
      - get: pdf-spike
      - task: look-up-book
        file: pdf-spike/bakery/tasks/t-book-lookup.yml
      - get: s3-job
      - task: assemble-book-via-neb
        file: pdf-spike/bakery/tasks/t-assemble-book.yml

    on_failure:
      put: event-update
      params:
        id: workflow-events-queued/id
        status_id: "4" #Failed
    on_success:
      put: s3-job-dir
      params:
        dir: workflow-events-queued/id
        glob: book/collection.assembled.xhtml

  - name: bake-book
    plan:
      - get: workflow-events-queued
        trigger: true
        passed: [assemble-book]
      - get: pdf-spike
      - task: look-up-book
        file: pdf-spike/bakery/tasks/t-book-lookup.yml
      - get: s3-job-dir
      - get: cnx-recipes
      - task: bake-book-via-easy-bake
        file: pdf-spike/bakery/tasks/t-bake-book.yml

    on_failure:
      put: event-update
      params:
        id: workflow-events-queued/id
        status_id: "4" #Failed
    on_success:
      put: s3-job-dir
      params:
        dir: workflow-events-queued/id
        glob: book/collection.baked.xhtml

  - name: mathify-book
    plan:
      - get: workflow-events-queued
        trigger: true
        passed: [bake-book]
      - get: pdf-spike
      - task: look-up-book
        file: pdf-spike/bakery/tasks/t-book-lookup.yml
      - get: s3-job-dir
      - task: mathify-book-via-mathify
        file: pdf-spike/bakery/tasks/t-mathify-book.yml

    on_failure:
      put: event-update
      params:
        id: workflow-events-queued/id
        status_id: "4" #Failed
    on_success:
      put: s3-job-dir
      params:
        dir: workflow-events-queued/id
        glob: book/collection.mathified.xhtml

  - name: generate-pdf
    plan:
      - get: workflow-events-queued
        trigger: true
        passed: [mathify-book]
      - get: pdf-spike
      - task: look-up-book
        file: pdf-spike/bakery/tasks/t-book-lookup.yml
      - get: s3-job-dir
      - task: pdf-book-via-princexml
        file: pdf-spike/bakery/tasks/t-build-pdf.yml
      - put: s3-job-dir
        params:
          dir: workflow-events-queued/id
          glob: artifacts/*.pdf

    on_failure:
      put: event-update
      params:
        id: workflow-events-queued/id
        status_id: "4" #Failed
    on_success:
      put: event-update
      params:
        id: workflow-events-queued/id
        status_id: "5"
        pdf_url: artifacts/pdf_url
