---
resource_types:
  - name: s3-simple
    type: docker-image
    source:
      repository: 18fgsa/s3-resource-simple

  - name: workflow-events
    type: docker-image
    source:
      repository: openstax/workflow-event-resource

resources:
  - name: s3
    type: s3-simple
    source:
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      bucket: ((s3bucket))
      region: ((s3region))
      options:
        - "--exclude '*'"
        - "--include 'book/*'"

  - name: s3-artifacts
    type: s3
    source:
      bucket: ((s3bucket))
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      skip_download: true
      regexp: artifacts/(.*).pdf

  - name: cnx-recipes
    type: git
    source:
      uri: https://github.com/openstax/cnx-recipes.git

  - name: job-instructions
    type: git
    source:
      uri: https://github.com/openstax/pdf-spike.git

  - name: workflow-events-queued
    type: workflow-events
    source:
      api_root: ((pdf-job-queue-url))
      status_id: 1

  - name: event-status-updater
    type: workflow-events
    source:
      api_root: ((pdf-job-queue-url))
      status_id: 0

jobs:
  - name: claim-work
    plan:
      - get: workflow-events-queued
        trigger: true
        version: every
      - put: event-status-updater
        params:
          id: workflow-events-queued/id
          status_id: "2" #Assigned

    on_success:
      put: event-status-updater
      params:
        id: workflow-events-queued/id
        status_id: "3" #Processing

  - name: fetch-book
    plan:
      - get: workflow-events-queued
        trigger: true
        passed: [claim-work]
      - get: job-instructions
      - task: look-up-book
        #file: pdf-spike/bakery/tasks/t-book-lookup.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/nebuchadnezzar
              tag: latest
          inputs:
            - name: workflow-events-queued
          outputs:
            - name: book-title
          run:
            path: /bin/bash
            args:
              - -cxe
              - |
                exec 2> >(tee book-title/stderr >&2)
                tail workflow-events-queued/*
                cp workflow-events-queued/id              book-title/id
                cp workflow-events-queued/collection_id   book-title/collection_id
                cp workflow-events-queued/version         book-title/version
                cp workflow-events-queued/content_server  book-title/server
                wget -q https://raw.githubusercontent.com/openstax/cnx-recipes/master/books.txt
                set +x
                . books.txt
                set -x
                for book_config in "${BOOK_CONFIGS[@]}"
                do
                  read -r book_name recipe_name _ book_colid _ <<< "$book_config"
                  if [ "$book_colid" == "$(cat book-title/collection_id)" ]
                  then
                    echo -n "$recipe_name" >book-title/recipe
                    echo -n "$book_name" >book-title/name
                  fi
                done
                echo -n latest >book-title/version
                if [ ! -f book-title/collection_id ]
                then
                  set +x
                  echo "Book not found" >book-title/stderr
                  exit 1
                fi
      - task: fetch-book-via-neb
        #file: pdf-spike/bakery/tasks/t-fetch-book.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/nebuchadnezzar
              tag: latest

          inputs:
            - name: book-title
          outputs:
            - name: book

          run:
            path: /bin/bash
            args:
              - -cxe
              - |
                exec 2> >(tee book/stderr >&2)
                cp book-title/id              book/id
                cp book-title/collection_id   book/collection_id
                cp book-title/version         book/version
                cp book-title/server          book/server
                cp book-title/name            book/name
                cp book-title/recipe          book/recipe
                neb get -r -d "./temp" "$(cat book-title/server | cut -f1 -d".")" "$(cat book-title/collection_id)" "$(cat book-title/version)"
                mv temp/* book

    on_failure:
      put: event-status-updater
      params:
        id: workflow-events-queued/id
        status_id: "4" #Failed
    on_success:
      put: s3

  - name: assemble-book
    plan:
      - get: job-instructions
        trigger: true
        passed: [fetch-book]
      - get: s3
      - task: assemble-book-via-neb
        #file: pdf-spike/bakery/tasks/t-assemble-book.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/nebuchadnezzar
              tag: latest

          inputs:
            - name: s3
          outputs:
            - name: book

          run:
            path: /bin/bash
            args:
              - -cxe
              - |
                exec 2> >(tee book/stderr >&2)
                rm -f s3/stderr
                neb assemble "s3/book" "./book"

    on_failure:
      put: event-status-updater
      params:
        id: s3/book/id
        status_id: "4" #Failed
    on_success:
      put: s3
      params:
        path: book

  - name: bake-book
    plan:
      - get: job-instructions
        trigger: true
        passed: [assemble-book]
      - get: s3
      - get: cnx-recipes
      - task: bake-book-via-easy-bake
        #file: pdf-spike/bakery/tasks/t-bake-book.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/cnx-easybake

          inputs:
            - name: s3
            - name: cnx-recipes
          outputs:
            - name: book

          run:
            path: /bin/bash
            args:
              - -cxe
              - |
                exec 2> >(tee book/stderr >&2)
                rm -f s3/stderr
                book_dir="book"
                cnx-easybake "cnx-recipes/recipes/output/$(cat s3/book/recipe).css" "s3/$book_dir/collection.assembled.xhtml" "$book_dir/collection.baked.xhtml"
                style_file="cnx-recipes/styles/output/$(cat s3/book/name)-pdf.css"
                if [ -f "$style_file" ]
                then
                  cp "$style_file" $book_dir/
                  sed -i "s%<\\/head>%<link rel=\"stylesheet\" type=\"text/css\" href=\"$(basename $style_file)\" />&%" "$book_dir/collection.baked.xhtml"
                fi

    on_failure:
      put: event-status-updater
      params:
        id: s3/book/id
        status_id: "4" #Failed
    on_success:
      put: s3
      params:
        path: book

  - name: mathify-book
    plan:
      - get: job-instructions
        trigger: true
        passed: [bake-book]
      - get: s3
      - task: mathify-book-via-mathify
        #file: pdf-spike/bakery/tasks/t-mathify-book.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/mathify
              tag: latest

          inputs:
            - name: s3
          outputs:
            - name: book

          run:
            path: /bin/bash
            args:
              - -cxe
              - |
                exec 2> >(tee book/stderr >&2)
                rm -f s3/stderr
                node /src/typeset/start -i "s3/book/collection.baked.xhtml" -o "book/collection.mathified.xhtml" -f svg

    on_failure:
      put: event-status-updater
      params:
        id: s3/book/id
        status_id: "4" #Failed
    on_success:
      put: s3
      params:
        path: book

  - name: generate-pdf
    plan:
      - get: job-instructions
        trigger: true
        passed: [mathify-book]
      - get: s3
      - task: pdf-book-via-princexml
        #file: pdf-spike/bakery/tasks/t-build-pdf.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/princexml
              tag: latest
          inputs:
            - name: s3
          outputs:
            - name: artifacts

          run:
            user: root
            path: /bin/bash
            args:
              - -cxe
              - |
                exec 2> >(tee s3/book/stderr >&2)
                rm -f artifacts/stderr
                prince -v --output="artifacts/$(cat s3/book/name).pdf" "s3/book/collection.assembled.xhtml"
                echo -n "https://ce-pdf-spike.s3.amazonaws.com/artifacts/$(cat s3/book/name).pdf" >artifacts/pdf_url
      - put: s3-artifacts
        params:
          file: artifacts/*.pdf
          acl: public-read
          content_type: application/pdf

    on_failure:
      put: event-status-updater
      params:
        id: s3/book/id
        status_id: "4" #Failed
    on_success:
      put: event-status-updater
      params:
        id: s3/book/id
        status_id: "5"
        pdf_url: artifacts/pdf_url
