---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openstax/nebuchadnezzar
    tag: latest

inputs:
  - name: s3-job-dir
outputs:
  - name: book

run:
  path: /bin/bash
  args:
    - -cxe
    - |
      exec 2> >(tee book/stderr >&2)
      rm -f s3-job-dir/stderr
      neb assemble "s3-job-dir/book" "./book"
