---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openstax/cnx-easybake

inputs:
  - name: workflow-events-queued
  - name: book-title
  - name: s3-job-dir
  - name: cnx-recipes
outputs:
  - name: book

run:
  path: /bin/bash
  args:
    - -cxe
    - |
      exec 2> >(tee book/stderr >&2)
      rm -f s3-job-dir/stderr
      book_dir="book"
      cnx-easybake "cnx-recipes/recipes/output/$(cat book-title/recipe).css" "s3-job-dir/$(cat workflow-events-queued/id)/$book_dir/collection.assembled.xhtml" "$book_dir/collection.baked.xhtml"
      style_file="cnx-recipes/styles/output/$(cat book-title/name)-pdf.css"
      if [ -f "$style_file" ]
      then
        cp "$style_file" $book_dir/
        sed -i "s%<\\/head>%<link rel=\"stylesheet\" type=\"text/css\" href=\"$(basename $style_file)\" />&%" "$book_dir/collection.baked.xhtml"
      fi
