---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openstax/princexml
    tag: latest
inputs:
  - name: book-title
  - name: s3-xhtml
outputs:
  - name: artifacts

run:
  user: root
  path: /bin/bash
  args:
    - -cxe
    - |
      exec 2> >(tee s3-xhtml/book/stderr >&2)
      rm -f s3-xhtml/stderr
      prince -v --output="artifacts/$(cat book-title/name).pdf" "s3-xhtml/book/collection.mathified.xhtml"
      echo -n "https://ce-pdf-spike.s3.amazonaws.com/artifacts/$(cat book-title/name).pdf" >artifacts/pdf_url
