---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openstax/princexml
    tag: latest
inputs:
  - name: s3
outputs:
  - name: artifacts

run:
  user: root
  path: /bin/bash
  args:
    - -cxe
    - |
      exec 2> >(tee s3/book/stderr >&2)
      rm -f artifacts/stderr
      prince -v --output="artifacts/$(cat s3/book/name).pdf" "s3/book/collection.assembled.xhtml"
      echo -n "https://ce-pdf-spike.s3.amazonaws.com/artifacts/$(cat s3/book/name).pdf" >artifacts/pdf_url
